<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <RootNamespace>MunicipalServicesApp</RootNamespace>
    <AssemblyName>MunicipalServicesApp</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
